version: 2
jobs:
  build:
    working_directory: ~/sunshinejr/danger-xiblint
    parallelism: 1
    shell: /bin/bash --login
    environment:
      LANG: en_US.UTF-8
    macos:
      xcode: '9.3.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-build-{{ .Branch }}-
      - run:
          name: Install xiblint
          command: pip install git+https://github.com/lyft/xiblint.git
      - run: 
          name: Update SPM
          command: swift update package
      - save_cache:
          key: v1-build-{{ .Branch }}-{{ epoch }}
          paths:
            - .build
      - run: 
          name: swift build
          command: swift build
      - run: 
          name: swift test
          command: swift test
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs          